[build]
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/items"
  to = "/.netlify/functions/items"
  status = 200

[[redirects]]
  from = "/vote"
  to = "/.netlify/functions/vote"
  status = 200